services:
  config-server:
    build:
      context: ./config-server
      dockerfile: Dockerfile
    container_name: config-server
    ports:
      - "${CONFIG_SERVER_PORT}:${CONFIG_SERVER_PORT}"
    environment:
      CONFIG_SERVER_PORT: ${CONFIG_SERVER_PORT}
  
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "${API_GATEWAY_PORT}:${API_GATEWAY_PORT}"
    depends_on:
      - config-server
  
  car-service:
    build:
      context: ./car-service
      dockerfile: Dockerfile
    container_name: car-service
    ports:
    - "${CAR_SERVICE_PORT}:${CAR_SERVICE_PORT}"
    environment:
      SERVER_PORT: ${CAR_SERVICE_PORT}
      CONFIG_SERVER_PORT: ${CONFIG_SERVER_PORT}
      SPRING_R2DBC_URL: r2dbc:postgresql://cars-db:${CARS_DB_PORT}/${CARS_DB_NAME}
      SPRING_R2DBC_USERNAME: ${CARS_DB_USER}
      SPRING_R2DBC_PASSWORD: ${CARS_DB_PASS}
      SPRING_FLYWAY_URL: jdbc:postgresql://cars-db:${CARS_DB_PORT}/${CARS_DB_NAME}
      SPRING_FLYWAY_USER: ${CARS_DB_USER}
      SPRING_FLYWAY_PASSWORD: ${CARS_DB_PASS}
    depends_on:
      - config-server
      - cars-db

  rabbit-mq:
    container_name: ${RABBIT_MQ_HOST}
    image: rabbitmq:3-management
    ports:
      - "${RABBIT_MQ_PORT}:${RABBIT_MQ_PORT}"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_MQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_MQ_PASS}

  cars-db:
    container_name: ${CARS_DB_NAME}
    image: ${CARS_DB_IMAGE}
    ports:
      - "${CARS_DB_PORT}:${CARS_DB_PORT}"
    environment:
      POSTGRES_USER: ${CARS_DB_USER}
      POSTGRES_PASSWORD: ${CARS_DB_PASS}
      POSTGRES_DB: ${CARS_DB_NAME}
    volumes:
      - cars-data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    restart: always
    command:
      - start-dev
      - --import-realm
    environment:
      KC_HTTP_PORT: ${KC_PORT}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:${KC_DB_PORT}/${KC_DB_NAME}
      KC_DB_USERNAME: ${KC_DB_USER}
      KC_DB_PASSWORD: ${KC_DB_PASS}
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_BOOTSTRAP_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_BOOTSTRAP_ADMIN_PASSWORD}
    volumes:
      - ./realm-ecoride.json:/opt/keycloak/data/import/realm-ecoride.json
    ports:
      - "${KC_PORT}:8180"
    depends_on:
      - keycloak-db

  keycloak-db:
    image: postgres:15
    container_name: keycloak-db
    restart: always
    environment:
      POSTGRES_DB: ${KC_DB_NAME}
      POSTGRES_USER: ${KC_DB_USER}
      POSTGRES_PASSWORD: ${KC_DB_PASS}
    volumes:
      - keycloak_data:/var/lib/postgresql/data

volumes:
  keycloak_data:
  cars-data:
