services:
  config-server:
    build:
      context: .
      dockerfile: ./config-server/Dockerfile
    container_name: config-server
    ports:
      - "${CONFIG_SERVER_PORT}:${CONFIG_SERVER_PORT}"
    environment:
      SERVER_PORT: ${CONFIG_SERVER_PORT}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://config-server:${CONFIG_SERVER_PORT}/actuator/health"]
      interval: 10s
      timeout: 2s
      retries: 10
      start_period: 30s
    profiles:
      - core
      - branch-car
      - branch-trip
      - branch-passenger
      - branch-notification
      - default
  
  eureka-server:
    build:
      context: .
      dockerfile: ./eureka-server/Dockerfile
    container_name: eureka-server
    ports:
      - "${EUREKA_SERVER_PORT}:${EUREKA_SERVER_PORT}"
    environment:
      SERVER_PORT: ${EUREKA_SERVER_PORT}
      CONFIG_SERVER_PORT: ${CONFIG_SERVER_PORT}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://eureka-server:${EUREKA_SERVER_PORT}/actuator/health"]
      interval: 10s
      timeout: 2s
      retries: 10
      start_period: 30s
    depends_on:
      config-server:
        condition: service_healthy
    profiles:
      - core
      - branch-car
      - branch-trip
      - branch-passenger
      - default

  api-gateway:
    build:
      context: .
      dockerfile: ./api-gateway/Dockerfile
    container_name: api-gateway
    ports:
      - "${API_GATEWAY_PORT}:${API_GATEWAY_PORT}"
    environment:
      SERVER_PORT: ${API_GATEWAY_PORT}
      CONFIG_SERVER_PORT: ${CONFIG_SERVER_PORT}
      CAR_SERVICE_PORT: ${CAR_SERVICE_PORT}
      TRIP_SERVICE_PORT: ${TRIP_SERVICE_PORT}
      EUREKA_SERVER_PORT: ${EUREKA_SERVER_PORT}
      KEYCLOACK_PORT: ${KC_PORT}
      GATEWAY_KEYCLOACK_CLIENT_SECRET: ${GATEWAY_KEYCLOACK_CLIENT_SECRET}
    depends_on:
      eureka-server:
        condition: service_healthy
    profiles:
      - core
      - branch-car
      - branch-trip
      - branch-passenger
      - default
  
  car-service:
    build:
      context: .
      dockerfile: ./car-service/Dockerfile
    container_name: car-service
    environment:
      SERVER_PORT: ${CAR_SERVICE_PORT}
      CONFIG_SERVER_PORT: ${CONFIG_SERVER_PORT}
      SPRING_R2DBC_URL: r2dbc:postgresql://cars-db:${CARS_DB_PORT}/${CARS_DB_NAME}
      SPRING_R2DBC_USERNAME: ${CARS_DB_USER}
      SPRING_R2DBC_PASSWORD: ${CARS_DB_PASS}
      SPRING_FLYWAY_URL: jdbc:postgresql://cars-db:${CARS_DB_PORT}/${CARS_DB_NAME}
      SPRING_FLYWAY_USER: ${CARS_DB_USER}
      SPRING_FLYWAY_PASSWORD: ${CARS_DB_PASS}
      EUREKA_SERVER_PORT: ${EUREKA_SERVER_PORT}
    depends_on:
      eureka-server:
        condition: service_healthy
      cars-db:
        condition: service_started 
    profiles:
      - branch-car
      - default
    
  trip-service:
    build:
      context: .
      dockerfile: ./trip-service/Dockerfile
    container_name: trip-service
    environment:
      SERVER_PORT: ${TRIP_SERVICE_PORT}
      CONFIG_SERVER_PORT: ${CONFIG_SERVER_PORT}
      SPRING_R2DBC_URL: r2dbc:postgresql://trips-db:${TRIPS_DB_PORT}/${TRIPS_DB_NAME}
      SPRING_R2DBC_USERNAME: ${TRIPS_DB_USER}
      SPRING_R2DBC_PASSWORD: ${TRIPS_DB_PASS}
      SPRING_FLYWAY_URL: jdbc:postgresql://trips-db:${TRIPS_DB_PORT}/${TRIPS_DB_NAME}
      SPRING_FLYWAY_USER: ${TRIPS_DB_USER}
      SPRING_FLYWAY_PASSWORD: ${TRIPS_DB_PASS}
      EUREKA_SERVER_PORT: ${EUREKA_SERVER_PORT}
      RABBIT_MQ_HOST: ${RABBIT_MQ_HOST}
      RABBIT_MQ_PORT: ${RABBIT_MQ_PORT}
      RABBIT_MQ_USER: ${RABBIT_MQ_USER}
      RABBIT_MQ_PASS: ${RABBIT_MQ_PASS}
    depends_on:
      eureka-server:
        condition: service_healthy
      trips-db:
        condition: service_started
    profiles:
      - branch-trip
      - default

  passenger-service:
    build:
      context: .
      dockerfile: ./passenger-service/Dockerfile
    container_name: passenger-service
    environment:
      SERVER_PORT: ${PASSENGER_SERVICE_PORT}
      CONFIG_SERVER_PORT: ${CONFIG_SERVER_PORT}
      SPRING_R2DBC_URL: r2dbc:postgresql://passengers-db:${PASSENGER_DB_PORT}/${PASSENGER_DB_NAME}
      SPRING_R2DBC_USERNAME: ${PASSENGER_DB_USER}
      SPRING_R2DBC_PASSWORD: ${PASSENGER_DB_PASS}
      SPRING_FLYWAY_URL: jdbc:postgresql://passengers-db:${PASSENGER_DB_PORT}/${PASSENGER_DB_NAME}
      SPRING_FLYWAY_USER: ${PASSENGER_DB_USER}
      SPRING_FLYWAY_PASSWORD: ${PASSENGER_DB_PASS}
      EUREKA_SERVER_PORT: ${EUREKA_SERVER_PORT}
    depends_on:
      eureka-server:
        condition: service_healthy
      passengers-db:
        condition: service_started
    
    profiles:
      - branch-passenger
      - default

  payment-service:
    build:
      context: .
      dockerfile: ./payment-service/Dockerfile
    container_name: payment-service
    environment:
      SERVER_PORT: ${PAYMENT_SERVICE_PORT}
      CONFIG_SERVER_PORT: ${CONFIG_SERVER_PORT}
      SPRING_R2DBC_URL: r2dbc:postgresql://payments-db:${PAYMENTS_DB_PORT}/${PAYMENTS_DB_NAME}
      SPRING_R2DBC_USERNAME: ${PAYMENTS_DB_USER}
      SPRING_R2DBC_PASSWORD: ${PAYMENTS_DB_PASS}
      SPRING_FLYWAY_URL: jdbc:postgresql://payments-db:${PAYMENTS_DB_PORT}/${PAYMENTS_DB_NAME}
      SPRING_FLYWAY_USER: ${PAYMENTS_DB_USER}
      SPRING_FLYWAY_PASSWORD: ${PAYMENTS_DB_PASS}
      EUREKA_SERVER_PORT: ${EUREKA_SERVER_PORT}
      RABBIT_MQ_HOST: ${RABBIT_MQ_HOST}
      RABBIT_MQ_PORT: ${RABBIT_MQ_PORT_AMQP}
      RABBIT_MQ_USER: ${RABBIT_MQ_USER}
      RABBIT_MQ_PASS: ${RABBIT_MQ_PASS}

    depends_on:
      eureka-server:
        condition: service_healthy
      trips-db:
        condition: service_started
      config-server:
        condition: service_healthy
      rabbit-mq:
        condition: service_started
    profiles:
      - branch-payment
      - default
    
  notification-service:
    build:
      context: .
      dockerfile: ./notification-service/Dockerfile
    container_name: notification-service
    environment:
      SERVER_PORT: ${NOTIFICATION_SERVICE_PORT}
      CONFIG_SERVER_PORT: ${CONFIG_SERVER_PORT}
      SPRING_R2DBC_URL: r2dbc:postgresql://notification-db:${NOTIFICATION_DB_PORT}/${NOTIFICATION_DB_NAME}
      SPRING_R2DBC_USERNAME: ${NOTIFICATION_DB_USER}
      SPRING_R2DBC_PASSWORD: ${NOTIFICATION_DB_PASS}
      SPRING_FLYWAY_URL: jdbc:postgresql://notification-db:${NOTIFICATION_DB_PORT}/${NOTIFICATION_DB_NAME}
      SPRING_FLYWAY_USER: ${NOTIFICATION_DB_USER}
      SPRING_FLYWAY_PASSWORD: ${NOTIFICATION_DB_PASS}
      EUREKA_SERVER_PORT: ${EUREKA_SERVER_PORT}
      RABBT_MQ_HOST: ${RABBIT_MQ_HOST}
      RABBIT_MQ_PORT: ${RABBIT_MQ_PORT_AMQP}
      RABBIT_MQ_USER: ${RABBIT_MQ_USER}
      RABBIT_MQ_PASS: ${RABBIT_MQ_PASS}
      SMTP_SERVER_HOST: ${SMTP_SERVER_HOST}
      SMTP_SERVER_PORT: ${SMTP_SERVER_PORT}
      SMTP_SERVER_USERNAME: ${SMTP_SERVER_PASSWORD}
    depends_on:
      eureka-server:
        condition: service_healthy
      notification-db: 
        condition: service_started
    profiles:
      - branch-notification
      - default

  rabbit-mq:
    container_name: ${RABBIT_MQ_HOST}
    image: rabbitmq:3-management
    ports:
      - "${RABBIT_MQ_PORT_AMQP}:${RABBIT_MQ_PORT_AMQP}"
      - "${RABBIT_MQ_PORT}:${RABBIT_MQ_PORT}"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_MQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_MQ_PASS}
    profiles:
      - core
      - branch-car
      - branch-trip
      - branch-passenger
      - branch-payment
      - default

  cars-db:
    container_name: ${CARS_DB_NAME}
    image: ${CARS_DB_IMAGE}
    environment:
      POSTGRES_USER: ${CARS_DB_USER}
      POSTGRES_PASSWORD: ${CARS_DB_PASS}
      POSTGRES_DB: ${CARS_DB_NAME}
    volumes:
      - cars-data:/var/lib/postgresql/data
    profiles:
      - branch-car
      - default

  trips-db:
    container_name: ${TRIPS_DB_NAME}
    image: ${TRIPS_DB_IMAGE}
    environment:
      POSTGRES_USER: ${TRIPS_DB_USER}
      POSTGRES_PASSWORD: ${TRIPS_DB_PASS}
      POSTGRES_DB: ${TRIPS_DB_NAME}
    volumes:
      - trips-data:/var/lib/postgresql/data
    profiles:
      - branch-trip
      - default

  payments-db:
    container_name: ${PAYMENTS_DB_NAME}
    image: ${PAYMENTS_DB_IMAGE}
    environment:
      POSTGRES_USER: ${PAYMENTS_DB_USER}
      POSTGRES_PASSWORD: ${PAYMENTS_DB_PASS}
      POSTGRES_DB: ${PAYMENTS_DB_NAME}
    volumes:
      - payments-data:/var/lib/postgresql/data
    profiles:
      - branch-payment
      - default

  passengers-db:
    container_name: ${PASSENGER_DB_NAME}
    image: ${PASSENGER_DB_IMAGE}
    environment:
      POSTGRES_USER: ${PASSENGER_DB_USER}
      POSTGRES_PASSWORD: ${PASSENGER_DB_PASS}
      POSTGRES_DB: ${PASSENGER_DB_NAME}
    volumes:
      - passengers-data:/var/lib/postgresql/data
    profiles:
      - branch-passenger
      - default
  

  notification-db:
    container_name: ${NOTIFICATION_DB_NAME}
    image: ${NOTIFICATION_DB_IMAGE}
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: ${NOTIFICATION_DB_USER}
      POSTGRES_PASSWORD: ${NOTIFICATION_DB_PASS}
      POSTGRES_DB: ${NOTIFICATION_DB_NAME}
    volumes:
      - notification-data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command:
      - start-dev
      - --import-realm
    environment:
      KC_HTTP_PORT: ${KC_PORT}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:${KC_DB_PORT}/${KC_DB_NAME}
      KC_DB_USERNAME: ${KC_DB_USER}
      KC_DB_PASSWORD: ${KC_DB_PASS}
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_BOOTSTRAP_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_BOOTSTRAP_ADMIN_PASSWORD}
      KC_HOSTNAME_PORT: ${KC_PORT}
      KC_HOSTNAME_STRICT: 'false'
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-ecoride.json
    ports:
      - "${KC_PORT}:${KC_PORT}"
    depends_on:
      - keycloak-db
    profiles:
      - auth
      - branch-car
      - branch-trip
      - branch-passenger
      - branch-payment
      - default

  keycloak-db:
    image: postgres:15
    container_name: keycloak-db
    ports:
      - "${KC_DB_PORT}:${KC_DB_PORT}"
    environment:
      POSTGRES_DB: ${KC_DB_NAME}
      POSTGRES_USER: ${KC_DB_USER}
      POSTGRES_PASSWORD: ${KC_DB_PASS}
    volumes:
      - keycloak-data:/var/lib/postgresql/data
    profiles:
      - auth
      - branch-car
      - branch-trip
      - branch-passenger
      - branch-payment
      - default

volumes:
  keycloak-data:
  cars-data:
  passengers-data:
  payments-data:
  notification-data:
  trips-data:
  grafana-data:
  loki-data:
