INSERT INTO channels (name) VALUES 
('sms'),
('smtp'),
('push');

INSERT INTO event_types (name) VALUES 
('USER_REGISTERED'),
('PASSWORD_RESET'),
('RESERVATION_CONFIRMATION'),
('RESERVATION REMINDER'),
('GENERIC_NOTIFICATION');

INSERT INTO status (name) VALUES 
('PENDING'),
('SENT'),
('FAILED');

