spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: car
          uri: lb://car-service
          predicates: 
            - Path=/api/v1/cars/**
eureka:
  instance:
    hostname: ${spring.application.name}
  client:
    service-url:
      defaultZone: http://eureka-server:${EUREKA_SERVER_PORT}/eureka
