spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: keycloak-token
          uri: http://keycloak:${KEYCLOACK_PORT}
          predicates:
            - Path=/api/v1/auth/login
          filters:
            - RewritePath=/api/v1/auth/login,/realms/ecoride/protocol/openid-connect/token
            - AddRequestHeader=Content-Type,application/x-www-form-urlencoded

        - id: passenger-register
          uri: lb://passenger-service
          predicates:
            - Path=/api/v1/auth/register
          filters:
            - StripPrefix=0

        - id: car
          uri: lb://car-service
          predicates: 
            - Path=/api/v1/cars/**

        - id: trip
          uri: lb://trip-service
          predicates:
            - Path=/api/v1/trips/**

        - id: passenger
          uri: lb://passenger-service
          predicates:
            - Path=/api/v1/passengers/**

        - id: payment
          uri: lib://payment-service
          predicates:
            - Path=/api/v1/payments/**

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:${KEYCLOACK_PORT}/realms/ecoride
      client:
        registration:
          keycloak-gateway:
            provider: keycloak
            client-id: api-gateway
            client-secret: ${GATEWAY_KEYCLOACK_CLIENT_SECRET}
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            issuer-uri: http://keycloak:${KEYCLOACK_PORT}/realms/ecoride

eureka:
  instance:
    hostname: ${spring.application.name}
  client:
    service-url:
      defaultZone: http://eureka-server:${EUREKA_SERVER_PORT}/eureka
