spring:
  application:
    name: config-server
  profiles:
    active:
    - native

  cloud:
    config:
      enabled: true
      server:
        native:
          search-locations:
          - classpath:/configurations
