server:
  port: ${CONFIG_SERVER_PORT}

spring:
  application:
    name: config-server
  profiles:
    active:
    - native

  cloud:
    config:
      enabled: true
      server:
        native:
          search-locations:
          - classpath:/configurations

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - prometheus
      base-path: /actuator
  
  endpoint:
    prometheus:
      access: unrestricted
